// G8: write the generated pages of the "How cercit works" pack from the real schema.
//
// Runs every migration in a local Postgres (PGlite, the same harness as the SQL tests), then
// reads the catalogue: tables, columns and foreign keys -> schema.md (Mermaid diagrams by area);
// sql/NNN files -> migrations.md; database functions, who may call them and the rights they
// check -> functions.md. Nothing is read from or written to Supabase.
//
// Run after adding a migration:  node scripts/how-it-works/generate.mjs
// Out: behind-the-scenes/how-it-works/{schema,migrations,functions}.md
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { migratedDb } from "../../tests/sql/harness.mjs";
import { KEY_FUNCTIONS } from "./key-functions.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SQL = join(ROOT, "sql");
const OUT = join(ROOT, "behind-the-scenes", "how-it-works");
mkdirSync(OUT, { recursive: true });

const { db, failures } = await migratedDb();
if (failures.length) throw new Error("migrations failed: " + failures.join("; "));
const q = async (sql) => (await db.query(sql)).rows;

const files = readdirSync(SQL).filter((f) => /^\d{3}_.*\.sql$/.test(f)).sort();
const fileText = Object.fromEntries(files.map((f) => [f, readFileSync(join(SQL, f), "utf8")]));
const today = new Date().toISOString().slice(0, 10);
const header = (title, what) =>
  `# ${title}\n\n_Generated by \`scripts/how-it-works/generate.mjs\` from the ${files.length} migrations (${files[0].slice(0, 3)}–${files.at(-1).slice(0, 3)}) on ${today}. Don't edit by hand: re-run the script._\n\n${what}\n\n[← Back to the overview](README.md)\n\n`;

// ---------------------------------------------------------------- areas
const AREAS = [
  ["Customers and applications", /^(customers|customer_addresses|customer_consents|applications|application_detail_groups|application_stage_events|vehicles|vehicle_quotations|dealers|states|tenants)$/],
  ["Documents and automatic checks", /^(documents|document_|application_document_requirements|kyc_face_matches|consent_texts)/],
  ["Bureau", /^(bureau_|lender_aliases|obligation_details)/],
  ["Income and bank", /^(income_assessments|bank_|salary_slips|form16_)/],
  ["Decisions and policy", /^(policy_|recommendations|credit_decisions|engine_decisions|override_logs|rule_set_snapshots|parameter_definitions|reason_codes|model_versions|fraud_signals)/],
  ["Pricing and employers", /^(rate_grid|employer|pricing_products)/],
  ["Loans and repayments", /^(loan_|repayment_mandates)/],
  ["Users and roles", /^(users|roles|permissions|role_|permission_conflicts|security_settings)$|^role_/],
  ["Settings, audit and simulation", /.*/],
];
const areaOf = (t) => AREAS.find(([, re]) => re.test(t))[0];

const tables = await q(`
  select c.relname as name, obj_description(c.oid) as comment,
         (select count(*) from pg_attribute a where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)::int as cols
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' order by 1`);
const columns = await q(`
  select c.relname as tbl, a.attname as col, format_type(a.atttypid, a.atttypmod) as type, a.attnotnull as notnull,
         exists (select 1 from pg_constraint k where k.conrelid = c.oid and k.contype = 'p' and a.attnum = any (k.conkey)) as pk,
         col_description(c.oid, a.attnum) as comment
  from pg_class c join pg_namespace n on n.oid = c.relnamespace join pg_attribute a on a.attrelid = c.oid
  where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped
  order by c.relname, a.attnum`);
const fks = await q(`
  select c.conrelid::regclass::text as tbl, a.attname as col, c.confrelid::regclass::text as ref
  from pg_constraint c join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
  join pg_namespace n on n.oid = (select relnamespace from pg_class where oid = c.conrelid)
  where c.contype = 'f' and n.nspname = 'public' order by 1, 2`);

// where each table was created
const createdIn = {};
for (const f of files) for (const m of fileText[f].matchAll(/CREATE TABLE (?:IF NOT EXISTS )?(?:public\.)?([a-z_0-9]+)/gi)) createdIn[m[1]] ??= f.slice(0, 3);

const colsOf = (t) => columns.filter((c) => c.tbl === t);
const fkCols = new Set(fks.map((f) => `${f.tbl}.${f.col}`));
const mType = (t) => t.replace(/\(.*\)/, "").replace(/\[\]/, "_array").replace(/ with(out)? time zone/, "").replace(/[^a-zA-Z0-9_]+/g, "_");

let schema = header(
  "Database schema",
  "Every table in the database, grouped by area. Each diagram shows the tables of one area with their key columns (PK = the row's own id, FK = a link to another table); a table from another area appears when something links to it. Under each diagram, every table's columns.",
);
schema += `**${tables.length} tables, ${columns.length} columns, ${fks.length} links.**\n\n`;
schema += AREAS.map(([a]) => `- [${a}](#${a.toLowerCase().replace(/[^a-z0-9 ]/g, "").replace(/ /g, "-")}) (${tables.filter((t) => areaOf(t.name) === a).length} tables)`).join("\n") + "\n\n";
for (const [area] of AREAS) {
  const ts = tables.filter((t) => areaOf(t.name) === area).map((t) => t.name);
  if (!ts.length) continue;
  const links = fks.filter((f) => ts.includes(f.tbl));
  const outside = [...new Set(links.map((f) => f.ref).filter((r) => !ts.includes(r)))];
  schema += `## ${area}\n\n\`\`\`mermaid\nerDiagram\n`;
  for (const t of ts) {
    const all = colsOf(t);
    const keyCols = all.filter((c) => c.pk || fkCols.has(`${t}.${c.col}`));
    if (!keyCols.length) keyCols.push(all[0]);
    schema += `  ${t} {\n${keyCols.map((c) => `    ${mType(c.type)} ${c.col}${c.pk ? " PK" : ""}${fkCols.has(`${t}.${c.col}`) ? (c.pk ? ", FK" : " FK") : ""}`).join("\n")}\n  }\n`;
  }
  for (const o of outside) {
    const pk = colsOf(o).filter((c) => c.pk);
    schema += `  ${o} {\n${(pk.length ? pk : colsOf(o).slice(0, 1)).map((c) => `    ${mType(c.type)} ${c.col}${c.pk ? " PK" : ""}`).join("\n")}\n  }\n`;
  }
  for (const f of links) schema += `  ${f.ref} ||--o{ ${f.tbl} : "${f.col}"\n`;
  schema += "```\n\n";
  for (const t of ts) {
    const info = tables.find((x) => x.name === t);
    schema += `<details><summary><b>${t}</b> (${info.cols} columns${createdIn[t] ? `, from ${createdIn[t]}` : ""})${info.comment ? `: ${info.comment}` : ""}</summary>\n\n| Column | Type | Required | Note |\n|---|---|---|---|\n`;
    for (const c of colsOf(t)) {
      const fk = fks.find((f) => f.tbl === t && f.col === c.col);
      const note = [c.pk ? "id" : "", fk ? `→ ${fk.ref}` : "", c.comment ?? ""].filter(Boolean).join("; ");
      schema += `| ${c.col} | ${c.type} | ${c.notnull ? "yes" : ""} | ${note.replace(/\|/g, "/")} |\n`;
    }
    schema += "\n</details>\n\n";
  }
}
writeFileSync(join(OUT, "schema.md"), schema);

// ---------------------------------------------------------------- migrations
const titleOf = (text) => {
  for (const raw of text.split("\n").slice(0, 12)) {
    const l = raw.replace(/^--\s?/, "").trim();
    if (!raw.startsWith("--") || !l || /^=+$/.test(l)) continue;
    if (/Intelligence Tool$/.test(l)) continue; // 001's first line is the product's name
    return l.replace(/^cercit\s+[—-]\s+/i, "").replace(/^\d{3}:\s*/, "");
  }
  return "";
};
let mig = header(
  "Migrations, in run order",
  "Each `sql/NNN_*.sql` file changes the database once, in this order. The first line of each file says what it does; the file itself explains why. Which ones have been run on the live database: `docs/migration-run-log.md`.",
);
mig += "| # | File | What it does | Tables it creates |\n|---|---|---|---|\n";
for (const f of files) {
  const made = Object.entries(createdIn).filter(([, n]) => n === f.slice(0, 3)).map(([t]) => t);
  mig += `| ${f.slice(0, 3)} | [\`${f}\`](../../sql/${f}) | ${titleOf(fileText[f]).replace(/\|/g, "/")} | ${made.join(", ")} |\n`;
}
writeFileSync(join(OUT, "migrations.md"), mig);

// ---------------------------------------------------------------- functions
const fns = await q(`
  select p.proname as name, pg_get_function_identity_arguments(p.oid) as args,
         pg_get_function_result(p.oid) as result, p.prosecdef as definer, p.prosrc as src,
         p.prorettype = 'trigger'::regtype as is_trigger,
         has_function_privilege('anon', p.oid, 'EXECUTE') as anon,
         has_function_privilege('authenticated', p.oid, 'EXECUTE') as authed
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f' and p.proname like 'fn\\_%'
  order by 1, 2`);
const lastDefined = {};
const describe = {};
for (const f of files) {
  const lines = fileText[f].split("\n");
  lines.forEach((l, i) => {
    const m = l.match(/^CREATE (?:OR REPLACE )?FUNCTION (?:public\.)?(fn_[a-z0-9_]+)\s*\(/i);
    if (!m) return;
    lastDefined[m[1]] = f.slice(0, 3);
    const notes = [];
    for (let k = i - 1; k >= 0 && lines[k].startsWith("--") && notes.length < 3; k--) {
      const t = lines[k].replace(/^--\s?/, "").trim();
      if (!t || /^=+$|^-+$/.test(t) || /^\d+\.\s/.test(t)) break;
      notes.unshift(t);
    }
    if (notes.length) describe[m[1]] = notes.join(" ");
  });
}
const STAGES = [
  ["Customer onboarding and tracking", /^fn_customer_|^fn_consent|^fn_document_upload|^fn_(check|upsert_customer)_address|^fn_mask_email|^fn_fresh_code_at/],
  ["Documents and automatic checks", /^fn_(document|doc_|reading|kyc|auto_|record_document_reading|record_face_match|face_matches)/],
  ["Bureau and income", /^fn_(bureau|lender|dpd|months_between|simulate_income|income|bank|record_income_detail|product_key)/],
  ["Credit engine and decisions", /^fn_(assess|run_policy_engine|generate_recommendation|in_principle|officer_decision|engine_|policy_facts|calculate_emi|case_employer|model_version|check_officer|decision_versions|tenure_cap|shortfall_tolerance|create_application|submit_full_application|generate_application_id)/],
  ["Staff screens", /^fn_staff_|^fn_list_|^fn_my_|^fn_audit_log|^fn_search/],
  ["Credit policy", /^fn_policy_|^fn_rule/],
  ["Pricing and employers", /^fn_(rate_grid|employer|gstin|pricing)/],
  ["Offer, agreement, disbursal and repayments", /^fn_(loan|repayment|offer|agreement|mandate|disburse|installment|after_approval|apr|emi|first_emi_date|add_working_days)/],
  ["Simulation and practice", /^fn_(sim|synthetic|practice)/],
  ["Privacy and data protection", /^fn_(pii_|erasure_|retention_)/],
  ["Users, roles and sign-in", /^fn_(user|role|login|record_failed|record_login|unlock|current_staff|is_|require|has_permission|sees_real|security|org|public_org|permission|admin_|first_conflict)/],
  ["Settings, switches and backups", /^fn_(settings|feature|flag|module|default_tenant)/],
  ["Other", /.*/],
];for (const f of files) {
  for (const m of fileText[f].matchAll(/^--\s+(?:\*\s+)?(fn_[a-z0-9_]+)(?:\([^)]*\))?\s*(?::|—|-)\s+(.+)$/gm)) {
    describe[m[1]] ??= m[2].trim();
  }
}
const rightsOf = (src) => {
  const r = new Set();
  for (const m of src.matchAll(/fn_require_(?:any_)?permission\(\s*(?:ARRAY\[)?([^)\]]*)/g)) for (const p of m[1].matchAll(/'([a-z.]+)'/g)) r.add(p[1]);
  return [...r];
};
let fnmd = header(
  "Database functions, by stage",
  "Almost everything the website and the AWS services ask of the database goes through these functions (a few public lookups, such as the rate grid and the switches, are read directly). **Who may call**: *visitor* = anyone with the public key, *signed in* = any signed-in user (the function then checks rights), *operator* = only the SQL editor, the scheduled jobs, the AWS services and other database functions. **Key functions are in bold**, first in each stage. **Rights** are the permissions the function checks first (see Roles on the website). Triggers (run by the database on a change) are listed at the end.",
);
const callable = fns.filter((f) => !f.is_trigger);
fnmd += `**${callable.length} functions, ${fns.length - callable.length} trigger functions.**\n\n`;
for (const [stage, re] of STAGES) {
  const list = callable
    .filter((f) => STAGES.find(([, r]) => r.test(f.name))[0] === stage)
    .sort((a, b) => Number(!(a.name in KEY_FUNCTIONS)) - Number(!(b.name in KEY_FUNCTIONS)) || a.name.localeCompare(b.name));
  if (!list.length) continue;
  fnmd += `## ${stage}\n\n| Function | What it does | Who may call | Rights it checks | From |\n|---|---|---|---|---|\n`;
  for (const f of list) {
    const who = f.anon ? "visitor" : f.authed ? "signed in" : "operator";
    const rights = rightsOf(f.src).join(", ") || (/fn_is_trusted_operator/.test(f.src) ? "operator only" : "");
    // a key function's plain-English line, else the note above it in its migration or a header line naming it
    const key = f.name in KEY_FUNCTIONS;
    const what = (KEY_FUNCTIONS[f.name] ?? describe[f.name] ?? "").replace(/\|/g, "/").slice(0, 300);
    const sig = `\`${f.name}(${f.args.replace(/\|/g, "/")})\``;
    fnmd += `| ${key ? `**${sig}**` : sig} | ${what} | ${who} | ${rights} | ${lastDefined[f.name] ?? ""} |\n`;
  }
  fnmd += "\n";
}
fnmd += "## Triggers\n\n| Trigger function | What it does | From |\n|---|---|---|\n";
for (const f of fns.filter((x) => x.is_trigger)) fnmd += `| \`${f.name}\` | ${(KEY_FUNCTIONS[f.name] ?? describe[f.name] ?? "").replace(/\|/g, "/").slice(0, 300)} | ${lastDefined[f.name] ?? ""} |\n`;
writeFileSync(join(OUT, "functions.md"), fnmd);

await db.close();
console.log(`schema.md: ${tables.length} tables; migrations.md: ${files.length} files; functions.md: ${callable.length} functions, ${fns.length - callable.length} triggers`);
