"""Writes sql/021_draft_policy_2026_09.sql.

Stores the unified credit rules (policy/credit-rules-2026.09.json, decisions
D1-D7) as a DRAFT policy version based on the active 2026.08 baseline. Settings
are copied unchanged from 2026.08. The draft goes live only after someone other
than its author approves it (Credit control, CC1).

Run: python scripts/gen-policy-draft-2026-09.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES = ROOT / "policy" / "credit-rules-2026.09.json"
OUT = ROOT / "sql" / "021_draft_policy_2026_09.sql"

document = json.dumps(json.loads(RULES.read_text(encoding="utf-8")), separators=(",", ":"))
assert "$zen$" not in document

sql = f"""-- cercit — draft policy version 2026.09: unified credit rules (backlog FD4.2)
-- GENERATED by scripts/gen-policy-draft-2026-09.py — edit the script, not this file.
--
-- One rule set replacing the separate browser and database engines, with the
-- credit-policy decisions of 17 Sep 2026 (docs/design/FD4-rule-definitions.md):
-- age over 65 at maturity and FOIR over 50% refer; one bounce refers, two or
-- more decline; strict payment-delay rule; one under-700 rule; missing reports
-- refer; 25 rules in all. Tested against a hand-written copy on 40 scenarios
-- and 3,000 generated cases (npm run test:rules).
--
-- Status: DRAFT. Nothing changes for applicants until an approver who is not
-- the author approves it and its effective date arrives.
--
-- Run order: after 017 (needs baseline 2026.08). Safe to re-run.

DO $draft$
DECLARE
  v_base UUID;
  v_id   UUID;
BEGIN
  SELECT id INTO v_base
  FROM policy_versions
  WHERE tenant_id = fn_default_tenant_id() AND product = 'CAR_NEW' AND version_code = '2026.08';

  IF v_base IS NULL THEN
    RAISE EXCEPTION 'baseline 2026.08 not found — run 017 first';
  END IF;

  IF EXISTS (
    SELECT 1 FROM policy_versions
    WHERE tenant_id = fn_default_tenant_id() AND product = 'CAR_NEW' AND version_code = '2026.09'
  ) THEN
    RAISE NOTICE 'policy version 2026.09 already exists, nothing to do';
    RETURN;
  END IF;

  INSERT INTO policy_versions (version_code, base_version_id, tier, rationale, regulatory_ref)
  VALUES (
    '2026.09', v_base, 'MATERIAL',
    'Unify the browser and database rule engines into one 25-rule set. Decisions D1-D7 (17 Sep 2026): '
    'age over 65 at maturity refers; FOIR over 50% refers; 1 bounce refers, 2+ decline; decline on 60+ DPD ever, '
    '90+ DPD or write-off in 12 months, or any DPD in the last 6 months, refer on 1-30 DPD in months 7-12; '
    'one under-700 rule; missing bureau, bank or income data refers; write-off, settled, enquiry, active-account, '
    'income-variance, average-balance and name-match checks carried over from the database engine.',
    NULL
  )
  RETURNING id INTO v_id;

  INSERT INTO policy_documents (policy_version_id, engine, document)
  VALUES (v_id, 'zen', $zen${document}$zen$::jsonb);

  INSERT INTO policy_parameters (policy_version_id, param_key, value)
  SELECT v_id, param_key, value FROM policy_parameters WHERE policy_version_id = v_base;
END
$draft$;

-- Check
-- SELECT version_code, status, tier, base_version_id IS NOT NULL AS has_base FROM policy_versions ORDER BY version_code;
"""

OUT.write_text(sql, encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}")
