"""Writes sql/019_submit_application_permission.sql.

fn_submit_full_application (sql/006) is about 150 lines. Rather than retype it
to add one permission check, this copies the function from 006 unchanged,
inserts the check as the first statement, pins the search path, and closes it
to callers who are not logged in.

Run: python scripts/gen-submit-permission.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "sql" / "006_submit_application.sql"
OUT = ROOT / "sql" / "019_submit_application_permission.sql"

text = SRC.read_text(encoding="utf-8").replace("\r\n", "\n")
start = text.index("CREATE OR REPLACE FUNCTION fn_submit_full_application(")
end_marker = "$$ LANGUAGE plpgsql SECURITY DEFINER;"
end = text.index(end_marker, start)
body = text[start:end]

main_begin = "\nBEGIN\n"
i = body.index(main_begin)
check = (
    "\nBEGIN\n"
    "  -- Staff only: the customer-facing apply flow gets its own function in the KYC module.\n"
    "  -- 006 catches every error in this block, so a refusal is returned as\n"
    "  -- {error: true, summary: 'permission denied: app.create'} with nothing written.\n"
    "  PERFORM fn_require_permission('app.create');\n\n"
)
body = body[:i] + check + body[i + len(main_begin):]

sql = f"""-- cercit — permission check on application submission (backlog FD2.2)
-- GENERATED by scripts/gen-submit-permission.py from sql/006 — edit the script, not this file.
--
-- Same function as 006 with one change at the top: the caller needs app.create
-- (or is a trusted operator, see 018). Execution is closed to callers who are
-- not logged in; the staff "new application" screen is the only caller today.
--
-- Run order: after 018. Safe to re-run.

{body}$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

REVOKE EXECUTE ON FUNCTION fn_submit_full_application(
  TEXT, TEXT, TEXT, DATE, TEXT, TEXT, TEXT, TEXT, TEXT,
  DECIMAL, DECIMAL, DECIMAL, INTEGER, TEXT, TEXT, TEXT, TEXT, DECIMAL, DECIMAL, INTEGER
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION fn_submit_full_application(
  TEXT, TEXT, TEXT, DATE, TEXT, TEXT, TEXT, TEXT, TEXT,
  DECIMAL, DECIMAL, DECIMAL, INTEGER, TEXT, TEXT, TEXT, TEXT, DECIMAL, DECIMAL, INTEGER
) TO authenticated;
"""

OUT.write_text(sql, encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}")
