"""Writes sql/017_seed_policy_2026_08.sql.

The rules document is docs/engine-evaluation/zen-policy.json, which matched the
current browser engine on 40 scenarios and 2,000 generated cases. Rates, caps and
fees are copied inside the SQL from rate_grid and employer_category_pricing, so
the seed carries exactly today's values rather than a retyped copy.

Run: python scripts/gen-policy-seed.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZEN = ROOT / "docs" / "engine-evaluation" / "zen-policy.json"
OUT = ROOT / "sql" / "017_seed_policy_2026_08.sql"

document = json.dumps(json.loads(ZEN.read_text(encoding="utf-8")), separators=(",", ":"))
assert "$zen$" not in document

# key, section, label, type, unit, min, max, description
DEFINITIONS = [
    ("bureau.band_min.approve", "bureau", "Approve band — lowest bureau score", "score", "score", 300, 900, "Lower bound of the band priced at the Approve base rate"),
    ("bureau.band_min.maybe", "bureau", "Maybe band — lowest bureau score", "score", "score", 300, 900, "Lower bound of the band routed to officer review"),
    ("pricing.base_rate.approve", "pricing", "Base rate — Approve band", "percent", "% p.a.", 5, 30, None),
    ("pricing.base_rate.maybe", "pricing", "Base rate — Maybe band", "percent", "% p.a.", 5, 30, None),
    ("caps.max_ltv_pct.approve", "collateral", "Max LTV — Approve band", "percent", "% of ex-showroom", 0, 150, "Decision 0.2: LTV measured on ex-showroom"),
    ("caps.max_ltv_pct.maybe", "collateral", "Max LTV — Maybe band", "percent", "% of ex-showroom", 0, 150, None),
    ("caps.max_foir_pct.approve", "income", "Max FOIR — Approve band", "percent", "% of net income", 0, 100, "Decision 0.1: FOIR on net salary + other income"),
    ("caps.max_foir_pct.maybe", "income", "Max FOIR — Maybe band", "percent", "% of net income", 0, 100, None),
    ("caps.max_tenure_months.approve", "tenure", "Max tenure — Approve band", "months", "months", 0, 120, None),
    ("caps.max_tenure_months.maybe", "tenure", "Max tenure — Maybe band", "months", "months", 0, 120, None),
]
for cat in ("a", "b", "c"):
    C = cat.upper()
    DEFINITIONS += [
        (f"pricing.loading.cat_{cat}", "pricing", f"Rate loading — Category {C}", "percent", "% p.a.", 0, 10, None),
        (f"caps.max_ltv_pct.cat_{cat}", "collateral", f"Max LTV — Category {C}", "percent", "% of ex-showroom", 0, 150, None),
        (f"caps.max_tenure_months.cat_{cat}", "tenure", f"Max tenure — Category {C}", "months", "months", 0, 120, None),
        (f"charges.processing_fee.cat_{cat}", "charges", f"Processing fee — Category {C}", "amount_inr", "INR", 0, 100000, "Shown in the Key Fact Statement"),
    ]


def lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


defs_sql = ",\n".join(
    f"  ({lit(k)}, {lit(s)}, {lit(l)}, {lit(t)}, {lit(u)}, {lit(mn)}, {lit(mx)}, {lit(d)})"
    for k, s, l, t, u, mn, mx, d in DEFINITIONS
)

band_params = [
    ("bureau.band_min.approve", "APPROVE", "score_band_min"),
    ("bureau.band_min.maybe", "MAYBE", "score_band_min"),
    ("pricing.base_rate.approve", "APPROVE", "rate_pct"),
    ("pricing.base_rate.maybe", "MAYBE", "rate_pct"),
    ("caps.max_ltv_pct.approve", "APPROVE", "max_ltv_pct"),
    ("caps.max_ltv_pct.maybe", "MAYBE", "max_ltv_pct"),
    ("caps.max_foir_pct.approve", "APPROVE", "max_foir_pct"),
    ("caps.max_foir_pct.maybe", "MAYBE", "max_foir_pct"),
    ("caps.max_tenure_months.approve", "APPROVE", "max_tenure_months"),
    ("caps.max_tenure_months.maybe", "MAYBE", "max_tenure_months"),
]
band_sql = "\n  UNION ALL ".join(
    f"SELECT {lit(k)}, to_jsonb({col}) FROM rate_grid "
    f"WHERE band_label = {lit(label)} AND vehicle_category = 'CAR' AND policy_version = '2026.08' AND is_active"
    for k, label, col in band_params
)
cat_sql = "\n  UNION ALL ".join(
    f"SELECT 'pricing.loading.cat_' || lower(category_code), to_jsonb(rate_loading_pct) FROM employer_category_pricing WHERE policy_version = '2026.08'\n"
    f"  UNION ALL SELECT 'caps.max_ltv_pct.cat_' || lower(category_code), to_jsonb(max_ltv_pct) FROM employer_category_pricing WHERE policy_version = '2026.08'\n"
    f"  UNION ALL SELECT 'caps.max_tenure_months.cat_' || lower(category_code), to_jsonb(max_tenure_months) FROM employer_category_pricing WHERE policy_version = '2026.08'\n"
    f"  UNION ALL SELECT 'charges.processing_fee.cat_' || lower(category_code), to_jsonb(processing_fee_inr) FROM employer_category_pricing WHERE policy_version = '2026.08'"
    for _ in [0]
)

sql = f"""-- cercit — baseline policy version 2026.08 (backlog FD1.3)
-- GENERATED by scripts/gen-policy-seed.py — edit the script, not this file.
--
-- Captures today's policy exactly: the rules document that matched the current
-- engine on 2,040 cases, and the rates, caps and fees currently in rate_grid and
-- employer_category_pricing. Marked as the pre-governance baseline: it has no
-- approver because it predates the approval process. Every later version must
-- be approved by someone other than its author.
--
-- Run order: after 016 (and 011, which holds the category pricing). Safe to re-run.

-- 1. What each setting is
INSERT INTO parameter_definitions (param_key, section, label, value_type, unit, min_value, max_value, description) VALUES
{defs_sql}
ON CONFLICT (param_key) DO NOTHING;

-- 2–4. The version, its content, then make it live — only if it does not exist yet
DO $seed$
DECLARE
  v_id    UUID;
  v_count INT;
BEGIN
  IF EXISTS (
    SELECT 1 FROM policy_versions
    WHERE tenant_id = fn_default_tenant_id() AND product = 'CAR_NEW' AND version_code = '2026.08'
  ) THEN
    RAISE NOTICE 'policy version 2026.08 already exists, nothing to do';
    RETURN;
  END IF;

  INSERT INTO policy_versions (version_code, is_baseline, rationale)
  VALUES (
    '2026.08', true,
    'Baseline: credit policy in force before versioned approvals (18 rules, rate grid, employer category pricing). Rules document matched the browser engine on 40 scenarios and 2,000 generated cases.'
  )
  RETURNING id INTO v_id;

  INSERT INTO policy_documents (policy_version_id, engine, document)
  VALUES (v_id, 'zen', $zen${document}$zen$::jsonb);

  INSERT INTO policy_parameters (policy_version_id, param_key, value)
  SELECT v_id, k, v FROM (
  {band_sql}
  UNION ALL {cat_sql}
  ) AS src(k, v);

  GET DIAGNOSTICS v_count = ROW_COUNT;
  IF v_count <> {len(DEFINITIONS)} THEN
    RAISE EXCEPTION 'expected {len(DEFINITIONS)} baseline parameters, found % — check rate_grid and employer_category_pricing (migration 011)', v_count;
  END IF;

  UPDATE policy_versions
  SET status = 'ACTIVE', effective_from = '2026-08-01 00:00:00+05:30'
  WHERE id = v_id;
END
$seed$;

-- Check
-- SELECT version_code, status, effective_from FROM policy_versions;
-- SELECT fn_policy_param('pricing.base_rate.approve');
-- SELECT version_code, document_sha256 FROM fn_policy_document_at();
"""

OUT.write_text(sql, encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)} with {len(DEFINITIONS)} parameters")
