-- cercit — Seed dealer data from indian_car_oem_dealers.csv
-- 132 dealers across 12 OEMs, 8 cities, 7 states
-- Run after 001_schema.sql and 002_seed_lookups.sql
--
-- The models CSV (355 records) feeds vehicle make/model/variant dropdowns
-- as static reference data — no DB table needed.

INSERT INTO dealers (dealer_code, dealer_name, make, city, state_code, is_active) VALUES
-- Hyundai (21)
('HYD-DEL-001','Ramaa Hyundai','Hyundai','Delhi','DL',true),
('HYD-DEL-002','Hans Hyundai','Hyundai','Delhi','DL',true),
('HYD-DEL-003','Hyundai Dwarka','Hyundai','Delhi','DL',true),
('HYD-DEL-004','Hyundai IP Extension','Hyundai','Delhi','DL',true),
('HYD-DEL-005','Hyundai Najafgarh','Hyundai','Delhi','DL',true),
('HYD-KOL-001','Hyundai Salt Lake','Hyundai','Kolkata','WB',true),
('HYD-KOL-002','Hyundai Kalikapur','Hyundai','Kolkata','WB',true),
('HYD-KOL-003','Hyundai Kharibari','Hyundai','Kolkata','WB',true),
('HYD-MUM-001','Hyundai Navi Mumbai','Hyundai','Mumbai','MH',true),
('HYD-MUM-002','Hyundai Mahalaxmi','Hyundai','Mumbai','MH',true),
('HYD-MUM-003','Hyundai Kandivali','Hyundai','Mumbai','MH',true),
('HYD-MUM-004','Hyundai Borivali','Hyundai','Mumbai','MH',true),
('HYD-PUN-001','Hyundai Warje Pune','Hyundai','Pune','MH',true),
('HYD-PUN-002','Hyundai Hadapsar Pune','Hyundai','Pune','MH',true),
('HYD-PUN-003','Hyundai Baner Pune','Hyundai','Pune','MH',true),
('HYD-AHM-001','Hyundai Vishala Ahmedabad','Hyundai','Ahmedabad','GJ',true),
('HYD-AHM-002','Gallops Hyundai Nikol','Hyundai','Ahmedabad','GJ',true),
('HYD-AHM-003','Gallops Hyundai Amraiwadi','Hyundai','Ahmedabad','GJ',true),
('HYD-BLR-001','Hyundai Bangalore','Hyundai','Bangalore','KA',true),
('HYD-CHN-001','Hyundai Chennai','Hyundai','Chennai','TN',true),
('HYD-HYD-001','Hyundai Hyderabad','Hyundai','Hyderabad','TS',true),
-- Maruti Arena (11)
('MAR-A-DEL-001','TR Sawhney Motors','Maruti Arena','Delhi','DL',true),
('MAR-A-DEL-002','Magic Auto','Maruti Arena','Delhi','DL',true),
('MAR-A-DEL-003','Rohan Motors','Maruti Arena','Delhi','DL',true),
('MAR-A-DEL-004','DD Motors','Maruti Arena','Delhi','DL',true),
('MAR-A-MUM-001','Maruti Arena Mumbai','Maruti Arena','Mumbai','MH',true),
('MAR-A-BLR-001','Maruti Arena Bangalore','Maruti Arena','Bangalore','KA',true),
('MAR-A-CHN-001','Maruti Arena Chennai','Maruti Arena','Chennai','TN',true),
('MAR-A-HYD-001','Maruti Arena Hyderabad','Maruti Arena','Hyderabad','TS',true),
('MAR-A-KOL-001','Maruti Arena Kolkata','Maruti Arena','Kolkata','WB',true),
('MAR-A-PUN-001','Maruti Arena Pune','Maruti Arena','Pune','MH',true),
('MAR-A-AHM-001','Maruti Arena Ahmedabad','Maruti Arena','Ahmedabad','GJ',true),
-- Maruti Nexa (12)
('MAR-N-DEL-001','Rana Nexa Kailash Colony','Maruti Nexa','Delhi','DL',true),
('MAR-N-DEL-002','Nexa Moti Nagar','Maruti Nexa','Delhi','DL',true),
('MAR-N-DEL-003','Nexa Shahdara','Maruti Nexa','Delhi','DL',true),
('MAR-N-DEL-004','Nexa GT Karnal Road','Maruti Nexa','Delhi','DL',true),
('MAR-N-DEL-005','Nexa Rohini','Maruti Nexa','Delhi','DL',true),
('MAR-N-MUM-001','Maruti Nexa Mumbai','Maruti Nexa','Mumbai','MH',true),
('MAR-N-BLR-001','Maruti Nexa Bangalore','Maruti Nexa','Bangalore','KA',true),
('MAR-N-CHN-001','Maruti Nexa Chennai','Maruti Nexa','Chennai','TN',true),
('MAR-N-HYD-001','Maruti Nexa Hyderabad','Maruti Nexa','Hyderabad','TS',true),
('MAR-N-KOL-001','Maruti Nexa Kolkata','Maruti Nexa','Kolkata','WB',true),
('MAR-N-PUN-001','Maruti Nexa Pune','Maruti Nexa','Pune','MH',true),
('MAR-N-AHM-001','Maruti Nexa Ahmedabad','Maruti Nexa','Ahmedabad','GJ',true),
-- Honda (10)
('HON-DEL-001','Honda Delhi','Honda','Delhi','DL',true),
('HON-MUM-001','Honda Mumbai','Honda','Mumbai','MH',true),
('HON-BLR-001','Magnum Honda Kanakapura','Honda','Bangalore','KA',true),
('HON-BLR-002','Magnum Honda Mehkri Circle','Honda','Bangalore','KA',true),
('HON-BLR-003','Tridentauto Honda Kengeri','Honda','Bangalore','KA',true),
('HON-CHN-001','Honda Chennai','Honda','Chennai','TN',true),
('HON-HYD-001','Honda Hyderabad','Honda','Hyderabad','TS',true),
('HON-KOL-001','Honda Kolkata','Honda','Kolkata','WB',true),
('HON-PUN-001','Honda Pune','Honda','Pune','MH',true),
('HON-AHM-001','Honda Ahmedabad','Honda','Ahmedabad','GJ',true),
-- Tata (12)
('TAT-DEL-001','Delight Motors Janakpuri','Tata','Delhi','DL',true),
('TAT-DEL-002','Sagar Motors Patparganj','Tata','Delhi','DL',true),
('TAT-DEL-003','Sparsh Narela','Tata','Delhi','DL',true),
('TAT-BLR-001','KHT Motors Whitefield','Tata','Bangalore','KA',true),
('TAT-BLR-002','Key Motors RR Nagar','Tata','Bangalore','KA',true),
('TAT-BLR-003','Adishakti Cars Dasarahalli','Tata','Bangalore','KA',true),
('TAT-MUM-001','Tata Mumbai','Tata','Mumbai','MH',true),
('TAT-CHN-001','Tata Chennai','Tata','Chennai','TN',true),
('TAT-HYD-001','Tata Hyderabad','Tata','Hyderabad','TS',true),
('TAT-KOL-001','Tata Kolkata','Tata','Kolkata','WB',true),
('TAT-PUN-001','Tata Pune','Tata','Pune','MH',true),
('TAT-AHM-001','Tata Ahmedabad','Tata','Ahmedabad','GJ',true),
-- Mahindra (12)
('MAH-DEL-001','Mahindra Karol Bagh','Mahindra','Delhi','DL',true),
('MAH-DEL-002','Mahindra Wazirabad Road','Mahindra','Delhi','DL',true),
('MAH-DEL-003','Mahindra Rama Road','Mahindra','Delhi','DL',true),
('MAH-DEL-004','Mahindra Lajpat Nagar','Mahindra','Delhi','DL',true),
('MAH-MUM-001','Mahindra Worli Mumbai','Mahindra','Mumbai','MH',true),
('MAH-MUM-002','Mahindra Goregaon Mumbai','Mahindra','Mumbai','MH',true),
('MAH-BLR-001','Mahindra Kottigepalya','Mahindra','Bangalore','KA',true),
('MAH-CHN-001','Mahindra Chennai','Mahindra','Chennai','TN',true),
('MAH-HYD-001','Mahindra Hyderabad','Mahindra','Hyderabad','TS',true),
('MAH-KOL-001','Mahindra Kolkata','Mahindra','Kolkata','WB',true),
('MAH-PUN-001','Mahindra Pune','Mahindra','Pune','MH',true),
('MAH-AHM-001','Mahindra Ahmedabad','Mahindra','Ahmedabad','GJ',true),
-- Toyota (10)
('TOY-DEL-001','Uttam Toyota','Toyota','Delhi','DL',true),
('TOY-DEL-002','Galaxy Toyota Shahdara','Toyota','Delhi','DL',true),
('TOY-DEL-003','Espirit Toyota','Toyota','Delhi','DL',true),
('TOY-BLR-001','Toyota Bangalore','Toyota','Bangalore','KA',true),
('TOY-MUM-001','Galaxy Toyota Mumbai','Toyota','Mumbai','MH',true),
('TOY-CHN-001','Toyota Chennai','Toyota','Chennai','TN',true),
('TOY-HYD-001','Toyota Hyderabad','Toyota','Hyderabad','TS',true),
('TOY-KOL-001','Toyota Kolkata','Toyota','Kolkata','WB',true),
('TOY-PUN-001','Toyota Pune','Toyota','Pune','MH',true),
('TOY-AHM-001','Toyota Ahmedabad','Toyota','Ahmedabad','GJ',true),
-- Kia (10)
('KIA-DEL-001','Allied Kia Connaught Place','Kia','Delhi','DL',true),
('KIA-DEL-002','Allied Kia Karol Bagh','Kia','Delhi','DL',true),
('KIA-DEL-003','Lohia Kia Wazirpur','Kia','Delhi','DL',true),
('KIA-MUM-001','Kia Mumbai','Kia','Mumbai','MH',true),
('KIA-BLR-001','Kia Bangalore','Kia','Bangalore','KA',true),
('KIA-CHN-001','Kia Chennai','Kia','Chennai','TN',true),
('KIA-HYD-001','Kia Hyderabad','Kia','Hyderabad','TS',true),
('KIA-KOL-001','Kia Kolkata','Kia','Kolkata','WB',true),
('KIA-PUN-001','Kia Pune','Kia','Pune','MH',true),
('KIA-AHM-001','Kia Ahmedabad','Kia','Ahmedabad','GJ',true),
-- Skoda (9)
('SKO-DEL-001','Skoda Paschim Vihar','Skoda','Delhi','DL',true),
('SKO-DEL-002','Skoda Delhi','Skoda','Delhi','DL',true),
('SKO-MUM-001','Skoda Mumbai','Skoda','Mumbai','MH',true),
('SKO-BLR-001','Skoda Bangalore','Skoda','Bangalore','KA',true),
('SKO-CHN-001','Skoda Chennai','Skoda','Chennai','TN',true),
('SKO-HYD-001','Skoda Hyderabad','Skoda','Hyderabad','TS',true),
('SKO-KOL-001','Skoda Kolkata','Skoda','Kolkata','WB',true),
('SKO-PUN-001','Skoda Pune','Skoda','Pune','MH',true),
('SKO-AHM-001','Skoda Ahmedabad','Skoda','Ahmedabad','GJ',true),
-- Volkswagen (9)
('VW-DEL-001','VW Moti Nagar','Volkswagen','Delhi','DL',true),
('VW-DEL-002','Atrica Automobiles','Volkswagen','Delhi','DL',true),
('VW-MUM-001','VW Mumbai','Volkswagen','Mumbai','MH',true),
('VW-BLR-001','VW Bangalore','Volkswagen','Bangalore','KA',true),
('VW-CHN-001','VW Chennai','Volkswagen','Chennai','TN',true),
('VW-HYD-001','VW Hyderabad','Volkswagen','Hyderabad','TS',true),
('VW-KOL-001','VW Kolkata','Volkswagen','Kolkata','WB',true),
('VW-PUN-001','VW Pune','Volkswagen','Pune','MH',true),
('VW-AHM-001','VW Ahmedabad','Volkswagen','Ahmedabad','GJ',true),
-- BYD (8)
('BYD-DEL-001','BYD Delhi','BYD','Delhi','DL',true),
('BYD-MUM-001','BYD Mumbai','BYD','Mumbai','MH',true),
('BYD-BLR-001','BYD Bangalore','BYD','Bangalore','KA',true),
('BYD-CHN-001','BYD Chennai','BYD','Chennai','TN',true),
('BYD-HYD-001','BYD Hyderabad','BYD','Hyderabad','TS',true),
('BYD-KOL-001','BYD Kolkata','BYD','Kolkata','WB',true),
('BYD-PUN-001','BYD Pune','BYD','Pune','MH',true),
('BYD-AHM-001','BYD Ahmedabad','BYD','Ahmedabad','GJ',true),
-- MG (8)
('MG-DEL-001','MG Delhi','MG','Delhi','DL',true),
('MG-MUM-001','MG Mumbai','MG','Mumbai','MH',true),
('MG-BLR-001','MG Bangalore','MG','Bangalore','KA',true),
('MG-CHN-001','MG Chennai','MG','Chennai','TN',true),
('MG-HYD-001','MG Hyderabad','MG','Hyderabad','TS',true),
('MG-KOL-001','MG Kolkata','MG','Kolkata','WB',true),
('MG-PUN-001','MG Pune','MG','Pune','MH',true),
('MG-AHM-001','MG Ahmedabad','MG','Ahmedabad','GJ',true)
ON CONFLICT (dealer_code) DO NOTHING;
