-- cercit — permission check on application submission (backlog FD2.2)
-- GENERATED by scripts/gen-submit-permission.py from sql/006 — edit the script, not this file.
--
-- Same function as 006 with one change at the top: the caller needs app.create
-- (or is a trusted operator, see 018). Execution is closed to callers who are
-- not logged in; the staff "new application" screen is the only caller today.
--
-- Run order: after 018. Safe to re-run.

CREATE OR REPLACE FUNCTION fn_submit_full_application(
  p_full_name TEXT,
  p_email TEXT,
  p_mobile TEXT,
  p_dob DATE DEFAULT NULL,
  p_pan TEXT DEFAULT NULL,
  p_employer TEXT DEFAULT NULL,
  p_city TEXT DEFAULT NULL,
  p_state_code TEXT DEFAULT NULL,
  p_pincode TEXT DEFAULT NULL,
  p_net_salary DECIMAL DEFAULT 0,
  p_existing_emis DECIMAL DEFAULT 0,
  p_loan_amount DECIMAL DEFAULT 0,
  p_tenure INTEGER DEFAULT 60,
  p_make TEXT DEFAULT NULL,
  p_model TEXT DEFAULT NULL,
  p_variant TEXT DEFAULT NULL,
  p_fuel_type TEXT DEFAULT 'PETROL',
  p_ex_showroom DECIMAL DEFAULT 0,
  p_on_road DECIMAL DEFAULT 0,
  p_cibil_score INTEGER DEFAULT 750
)
RETURNS JSONB AS $$
DECLARE
  created JSONB;
  app_uuid UUID;
  cust_uuid UUID;
  app_id TEXT;
  age_val INTEGER;
  dealer_uuid UUID;
  assess_result JSONB;
  rec_result JSONB;
BEGIN
  -- Staff only: the customer-facing apply flow gets its own function in the KYC module.
  -- 006 catches every error in this block, so a refusal is returned as
  -- {error: true, summary: 'permission denied: app.create'} with nothing written.
  PERFORM fn_require_permission('app.create');

  -- Step 1: Create application + customer
  created := fn_create_application(p_full_name, p_email, p_mobile);
  app_uuid := (created->>'application_uuid')::UUID;
  cust_uuid := (created->>'customer_id')::UUID;
  app_id := created->>'application_id';

  -- Calculate age
  IF p_dob IS NOT NULL THEN
    age_val := extract(year FROM age(p_dob))::INTEGER;
  ELSE
    age_val := 30;
  END IF;

  -- Step 2: Update customer details
  UPDATE customers SET
    date_of_birth = p_dob,
    age_at_application = age_val,
    pan_number = p_pan,
    employer_name = p_employer,
    employment_type = 'SALARIED',
    city = p_city,
    state_code = p_state_code,
    pincode = p_pincode
  WHERE id = cust_uuid;

  -- Step 3: Update application with financials
  UPDATE applications SET
    loan_amount_requested = p_loan_amount,
    tenure_months = p_tenure,
    declared_net_salary = p_net_salary,
    declared_existing_emis = p_existing_emis,
    status = 'UNDER_ASSESSMENT'
  WHERE id = app_uuid;

  -- Step 4: Insert vehicle
  SELECT id INTO dealer_uuid FROM dealers
    WHERE lower(make) LIKE '%' || lower(p_make) || '%'
    LIMIT 1;

  INSERT INTO vehicles (
    application_id, make, model, variant, fuel_type,
    ex_showroom_price, road_tax, insurance, registration_charges,
    on_road_price, vehicle_category, dealer_id
  ) VALUES (
    app_uuid, p_make, p_model, p_variant, p_fuel_type,
    p_ex_showroom,
    round(p_ex_showroom * 0.065),
    round(p_ex_showroom * 0.04),
    round(p_on_road - p_ex_showroom - p_ex_showroom * 0.065 - p_ex_showroom * 0.04),
    p_on_road, 'CAR', dealer_uuid
  );

  -- Step 5: Insert bureau report
  INSERT INTO bureau_reports (
    application_id, customer_id, bureau_name, score, score_date,
    dpd_max_12m, dpd_60_plus_flag, active_accounts,
    total_outstanding, total_monthly_emi,
    enquiry_count_90d, writeoff_count_5y, settled_count_5y,
    credit_utilization_pct
  ) VALUES (
    app_uuid, cust_uuid, 'CIBIL', p_cibil_score, current_date,
    0, false, 1,
    0, p_existing_emis,
    1, 0, 0,
    15
  );

  -- Step 6: Insert bank statement analysis
  INSERT INTO bank_statement_analyses (
    application_id, customer_id, bank_name, account_number_last4,
    statement_from, statement_to, months_covered,
    avg_monthly_balance, avg_salary_credit, salary_regularity,
    bounce_count_6m,
    amb_on_5th, amb_on_10th, amb_on_15th, amb_on_20th, amb_on_25th,
    min_amb_5dates
  ) VALUES (
    app_uuid, cust_uuid, 'HDFC', '1234',
    current_date - interval '6 months', current_date, 6,
    round(p_net_salary * 1.1), p_net_salary, 'REGULAR',
    0,
    round(p_net_salary * 1.1), round(p_net_salary * 1.15),
    round(p_net_salary * 1.08), round(p_net_salary * 1.12),
    round(p_net_salary * 1.1), round(p_net_salary * 1.08)
  );

  -- Step 7: Insert income assessment
  INSERT INTO income_assessments (
    application_id, declared_net_salary, salary_slip_salary,
    bank_credit_salary, form16_annual_income, form16_monthly_equiv,
    income_variance_pct, income_variance_flag,
    eligible_net_salary, name_match_score
  ) VALUES (
    app_uuid, p_net_salary, p_net_salary,
    p_net_salary, p_net_salary * 12, p_net_salary,
    0, false,
    p_net_salary, 100
  );

  -- Step 8: Run assessment pipeline
  assess_result := fn_assess_application(app_uuid);

  RETURN jsonb_build_object(
    'application_id', app_id,
    'application_uuid', app_uuid,
    'decision', coalesce(assess_result->'recommendation'->>'decision', assess_result->'policy'->>'decision', assess_result->>'decision'),
    'rate', coalesce(assess_result->'recommendation'->>'rate', assess_result->'policy'->>'rate', assess_result->>'rate'),
    'summary', coalesce(assess_result->'recommendation'->>'summary', assess_result->>'summary'),
    'assessment', assess_result
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object(
    'application_id', app_id,
    'application_uuid', app_uuid,
    'decision', 'ERROR',
    'rate', 0,
    'summary', SQLERRM,
    'error', true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

REVOKE EXECUTE ON FUNCTION fn_submit_full_application(
  TEXT, TEXT, TEXT, DATE, TEXT, TEXT, TEXT, TEXT, TEXT,
  DECIMAL, DECIMAL, DECIMAL, INTEGER, TEXT, TEXT, TEXT, TEXT, DECIMAL, DECIMAL, INTEGER
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION fn_submit_full_application(
  TEXT, TEXT, TEXT, DATE, TEXT, TEXT, TEXT, TEXT, TEXT,
  DECIMAL, DECIMAL, DECIMAL, INTEGER, TEXT, TEXT, TEXT, TEXT, DECIMAL, DECIMAL, INTEGER
) TO authenticated;
