-- cercit — keep policy history in the order it happened (fix to 032)
--
-- Events were ordered by their timestamp alone. Two steps recorded in the same
-- instant — sending a change for approval and taking it straight back, say —
-- could then be listed the wrong way round, which reads as a different story
-- than the one that happened. A counter gives every event a fixed place in the
-- order, and the timestamp still decides between events recorded at different
-- times.
--
-- Run order: after 034. Safe to re-run.

ALTER TABLE policy_version_events
  ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Rows written before this column existed keep their timestamp order.
UPDATE policy_version_events e
SET seq = o.rn
FROM (SELECT id, row_number() OVER (ORDER BY at, id) AS rn FROM policy_version_events WHERE seq IS NULL) o
WHERE o.id = e.id AND e.seq IS NULL;

SELECT setval(pg_get_serial_sequence('policy_version_events', 'seq'),
              GREATEST(COALESCE((SELECT max(seq) FROM policy_version_events), 0), 1));

CREATE OR REPLACE FUNCTION fn_policy_history(p_version_id UUID DEFAULT NULL)
RETURNS TABLE (
  version_id    UUID,
  version_code  VARCHAR,
  at            TIMESTAMPTZ,
  event         TEXT,
  actor         VARCHAR,
  note          TEXT,
  reconstructed BOOLEAN
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM fn_require_any_permission(ARRAY['policy.view', 'policy.author', 'policy.approve', 'audit.view']);

  RETURN QUERY
  SELECT h.version_id, h.version_code, h.at, h.event, h.actor, h.note, h.reconstructed FROM (
    SELECT v.id AS version_id, v.version_code, e.at,
           CASE
             WHEN e.from_status IS NULL AND e.to_status = 'DRAFT' THEN 'Drafted'
             WHEN e.from_status = 'DRAFT' AND e.to_status = 'PENDING_APPROVAL' THEN 'Sent for approval'
             WHEN e.from_status = 'PENDING_APPROVAL' AND e.to_status = 'DRAFT' THEN 'Taken back by its author'
             WHEN e.to_status = 'APPROVED' THEN 'Approved'
             WHEN e.to_status = 'REJECTED' THEN 'Rejected'
             WHEN e.to_status = 'ACTIVE' THEN 'Came into force'
             WHEN e.to_status = 'SUPERSEDED' THEN 'Replaced by a newer version'
             WHEN e.to_status = 'CANCELLED' THEN 'Cancelled'
             ELSE initcap(replace(e.to_status, '_', ' '))
           END AS event,
           COALESCE(u.full_name, CASE WHEN e.to_status IN ('ACTIVE', 'SUPERSEDED', 'CANCELLED') THEN 'System' END)::VARCHAR AS actor,
           CASE WHEN e.to_status = 'APPROVED' THEN 'Starts ' || to_char(v.effective_from AT TIME ZONE 'Asia/Kolkata', 'DD Mon YYYY') END AS note,
           e.reconstructed,
           e.seq AS order_within_moment
    FROM policy_version_events e
    JOIN policy_versions v ON v.id = e.policy_version_id
    LEFT JOIN users u ON u.id = e.actor_id
    WHERE p_version_id IS NULL OR v.id = p_version_id

    UNION ALL
    -- What the author said when sending it, including any withdrawal note
    SELECT v.id, v.version_code, cr.created_at, 'Change request', u.full_name::VARCHAR,
           concat_ws(chr(10), cr.title, cr.summary), false, 0
    FROM policy_change_requests cr
    JOIN policy_versions v ON v.id = cr.policy_version_id
    LEFT JOIN users u ON u.id = cr.requested_by
    WHERE p_version_id IS NULL OR v.id = p_version_id

    UNION ALL
    -- What the reviewer said
    SELECT v.id, v.version_code, rv.reviewed_at,
           CASE rv.decision WHEN 'APPROVE' THEN 'Review: approve' WHEN 'REJECT' THEN 'Review: reject' ELSE 'Review: sent back' END,
           u.full_name::VARCHAR, rv.comment, false, 0
    FROM policy_change_reviews rv
    JOIN policy_change_requests cr ON cr.id = rv.change_request_id
    JOIN policy_versions v ON v.id = cr.policy_version_id
    LEFT JOIN users u ON u.id = rv.reviewer_id
    WHERE p_version_id IS NULL OR v.id = p_version_id
  ) h
  ORDER BY h.at DESC, h.order_within_moment DESC;
END;
$$;

REVOKE ALL ON FUNCTION fn_policy_history(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION fn_policy_history(UUID) TO authenticated;

-- Check after running:
-- SELECT version_code, event, actor FROM fn_policy_history() LIMIT 10;
